var socialData = 

{
"login": "tinaconway",
"id": 12474662,
"avatar_url": "https://avatars.githubusercontent.com/u/12474662?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/tinaconway",
"html_url": "https://github.com/tinaconway",
"followers_url": "https://api.github.com/users/tinaconway/followers",
"following_url": "https://api.github.com/users/tinaconway/following{/other_user}",
"gists_url": "https://api.github.com/users/tinaconway/gists{/gist_id}",
"starred_url": "https://api.github.com/users/tinaconway/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/tinaconway/subscriptions",
"organizations_url": "https://api.github.com/users/tinaconway/orgs",
"repos_url": "https://api.github.com/users/tinaconway/repos",
"events_url": "https://api.github.com/users/tinaconway/events{/privacy}",
"received_events_url": "https://api.github.com/users/tinaconway/received_events",
"type": "User",
"site_admin": false,
"name": "Tina Conway",
"company": "",
"blog": "",
"location": "",
"email": "",
"hireable": false,
"bio": null,
"public_repos": 16,
"public_gists": 0,
"followers": 0,
"following": 0,
"created_at": "2015-05-16T16:00:58Z",
"updated_at": "2015-05-21T15:43:14Z"
}
